
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/test;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace;
spring.jpa.hibernate.ddl-auto=create


#JWTtoken configurations
jwt.secretKey=asd19i23hj909sfua9s0fdusd90fua9023fjnh
jwt.access.expiration=3600000
jwt.access.header=Authorization
jwt.refresh.expiration=1209600000
jwt.refresh.header=Set-Cookie

#OAuth2 google
spring.security.oauth2.client.registration.google.client-id=574121728411-si5ub2jih5ua9h8jtt0jatf72qsrt00p.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

server.port=8080

